<?php

namespace Database\Seeders;
use App\Models\boilerplate\RolePermission\Permission;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $modules = array( 
            ['name'=>'notify','guard_name'=>'web','display_name'=>'notification of doc expire','slug'=>'','category'=>'nav-notify','description'=>'notification of doc expire','created_at'=>NOW(),'updated_at'=>NOW()],
            ['name'=>'edit-users','guard_name'=>'web','display_name'=>'edit users','slug'=>'','category'=>'user','description'=>'edit users','created_at'=>NOW(),'updated_at'=>NOW()],
            ['name'=>'updated-document','guard_name'=>'web','display_name'=>'updated document','slug'=>'','category'=>'driver','description'=>'updated document','created_at'=>NOW(),'updated_at'=>NOW()],
            ['name'=>'submit-driver-detail','guard_name'=>'web','display_name'=>'submit driver detail','slug'=>'','category'=>'driver','description'=>'submit driver detail','created_at'=>NOW(),'updated_at'=>NOW()],
            ['name'=>'profile-bar','guard_name'=>'web','display_name'=>'profile bar','slug'=>'','category'=>'sidebars','description'=>'profile bar','created_at'=>NOW(),'updated_at'=>NOW()],
            ['name'=>'account-settings-bar','guard_name'=>'web','display_name'=>'account settings bar','slug'=>'','category'=>'sidebars','description'=>'account settings bar','created_at'=>NOW(),'updated_at'=>NOW()],
            ['name'=>'dashboard-bar','guard_name'=>'web','display_name'=>'dasnboard bar','slug'=>'','category'=>'sidebars','description'=>'dashboard bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'approved-driver-document','guard_name'=>'web','display_name'=>'approved driver document','slug'=>'','category'=>'driver','description'=>'approved driver document','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'denait-driver-document','guard_name'=>'web','display_name'=>'denait driver document','slug'=>'','category'=>'driver','description'=>'denait driver document','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-driver-document','guard_name'=>'web','display_name'=>'edit driver document','slug'=>'','category'=>'driver','description'=>'edit driver document','created_at'=>NOW(),'updated_at'=>NOW()],    
        ['name'=>'office-bar','guard_name'=>'web','display_name'=>'office-bar','slug'=>'','category'=>'sidebars','description'=>'office-bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'general','guard_name'=>'web','display_name'=>'general','slug'=>'','category'=>'settings','description'=>'general','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'installation-setting','guard_name'=>'web','display_name'=>'installation setting','slug'=>'','category'=>'settings','description'=>'installation setting','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'wallet','guard_name'=>'web','display_name'=>'wallet','slug'=>'','category'=>'settings','description'=>'wallet','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'trip-setting','guard_name'=>'web','display_name'=>'trip setting','slug'=>'','category'=>'settings','description'=>'trip setting','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'banned-version','guard_name'=>'web','display_name'=>'banned version','slug'=>'','category'=>'version','description'=>'banned version','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'reports-bar','guard_name'=>'web','display_name'=>'reports bar','slug'=>'','category'=>'sidebars','description'=>'reports bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-promocode','guard_name'=>'web','display_name'=>'edit promocode','slug'=>'','category'=>'promocode','description'=>'edit promocode','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'active-model','guard_name'=>'web','display_name'=>'active model','slug'=>'','category'=>'vehiclemodel','description'=>'active model','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-model','guard_name'=>'web','display_name'=>'delete model','slug'=>'','category'=>'vehiclemodel','description'=>'delete-model','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-model','guard_name'=>'web','display_name'=>'edit model','slug'=>'','category'=>'vehiclemodel','description'=>'edit model','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-model','guard_name'=>'web','display_name'=>'new model','slug'=>'','category'=>'vehiclemodel','description'=>'new model','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'status-change-outofzone','guard_name'=>'web','display_name'=>'status change outofzone','slug'=>'','category'=>'','description'=>'status change outofzone','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-outofzone','guard_name'=>'web','display_name'=>'delete outofzone','slug'=>'','category'=>'outofzone','description'=>'delete outofzone','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-outofzone','guard_name'=>'web','display_name'=>'edit outofzone','slug'=>'','category'=>'outofzone','description'=>'edit outofzone','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-outofzone','guard_name'=>'web','display_name'=>'new outofzone','slug'=>'','category'=>'outofzone','description'=>'new outofzone','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'setprice-outstation','guard_name'=>'web','display_name'=>'setprice outstation','slug'=>'','category'=>'outstation','description'=>'setprice outstation','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'status-change-outstation','guard_name'=>'web','display_name'=>'status change outstation','slug'=>'','category'=>'outstation','description'=>'status change outstation','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-outstation','guard_name'=>'web','display_name'=>'delete outstation','slug'=>'','category'=>'outstation','description'=>'delete outstation','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit outstation','guard_name'=>'web','display_name'=>'edit outstation','slug'=>'','category'=>'outstation','description'=>'edit outstation','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-outstation','guard_name'=>'web','display_name'=>'new outstation','slug'=>'','category'=>'outstation','description'=>'new outstation','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'status-change-cancelrequest','guard_name'=>'web','display_name'=>'status change cancelrequest','slug'=>'','category'=>'cancelrequest','description'=>'status change cancelrequest','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-cancelrequest','guard_name'=>'web','display_name'=>'delete cancelrequest','slug'=>'','category'=>'cancelrequest','description'=>'delete cancelrequest','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-cancelrequest','guard_name'=>'web','display_name'=>'edit cancelrequest','slug'=>'','category'=>'cancelrequest','description'=>'edit cancelrequest','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'request-edit','guard_name'=>'web','display_name'=>'request edit','slug'=>'','category'=>'request','description'=>'request edit','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'request-delete','guard_name'=>'web','display_name'=>'request delete','slug'=>'','category'=>'request','description'=>'request delete','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'request-view','guard_name'=>'web','display_name'=>'','slug'=>'','category'=>'request','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'dispatcher-edit','guard_name'=>'web','display_name'=>'dispatcher-edit','slug'=>'','category'=>'dispatcher','description'=>'dispatcher edit','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'dispatcher-delete','guard_name'=>'web','display_name'=>'dispatcher delete','slug'=>'','category'=>'dispatcher','description'=>'dispatcher delete','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'dispatcherrequest-view','guard_name'=>'web','display_name'=>'dispatcherrequest view','slug'=>'','category'=>'dispatcher','description'=>'dispatcherrequest view','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'inactive-drivers','guard_name'=>'web','display_name'=>'inactive drivers','slug'=>'','category'=>'driver','description'=>'inactive drivers','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'active-drivers','guard_name'=>'web','display_name'=>'active drivers','slug'=>'driver','category'=>'driver','description'=>'active drivers','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'view-driver','guard_name'=>'web','display_name'=>'view driver','slug'=>'','category'=>'driver','description'=>'view driver','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-users','guard_name'=>'web','display_name'=>'delete users','slug'=>'','category'=>'user','description'=>'delete users','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'active-users','guard_name'=>'web','display_name'=>'active-users','slug'=>'','category'=>'user','description'=>'active users','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'view-users','guard_name'=>'web','display_name'=>'view users','slug'=>'','category'=>'user','description'=>'view users','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'inactive-users','guard_name'=>'web','display_name'=>'inactive users','slug'=>'','category'=>'user','description'=>'inactive users','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'active-users','guard_name'=>'web','display_name'=>'active users','slug'=>'','category'=>'user','description'=>'active users','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'company-change-password','guard_name'=>'web','display_name'=>'company change password','slug'=>'','category'=>'company','description'=>'company change password','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'status-change-company','guard_name'=>'web','display_name'=>'status change company','slug'=>'','category'=>'company','description'=>'status change company','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-company','guard_name'=>'web','display_name'=>'delete company','slug'=>'','category'=>'company','description'=>'delete company','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-company','guard_name'=>'web','display_name'=>'edit company','slug'=>'','category'=>'company','description'=>'edit company','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'add-company','guard_name'=>'web','display_name'=>'add company','slug'=>'','category'=>'company','description'=>'add company','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-user','guard_name'=>'web','display_name'=>'new user','slug'=>'','category'=>'admin','description'=>'new user','created_at'=>NOW(),'updated_at'=>NOW()],    
        ['name'=>'edit-user','guard_name'=>'web','display_name'=>'admin edit','slug'=>'','category'=>'admin','description'=>'admin edit','created_at'=>NOW(),'updated_at'=>NOW()],   
        ['name'=>'delete-user','guard_name'=>'web','display_name'=>'delete user','slug'=>'','category'=>'admin','description'=>'delete user','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'status-change-user','guard_name'=>'web','display_name'=>'status change user','slug'=>'','category'=>'admin','description'=>'status change user','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'user-change-password','guard_name'=>'web','display_name'=>'password change user','slug'=>'','category'=>'admin','description'=>'password change user','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'mapview-bar','guard_name'=>'web','display_name'=>'map view','slug'=>'','category'=>'sidebars','description'=>'map view','created_at'=>NOW(),'updated_at'=>NOW()], 
        ['name'=>'user-management-bar','guard_name'=>'web','display_name'=>'user management','slug'=>'','category'=>'sidebars','description'=>'user management','created_at'=>NOW(),'updated_at'=>NOW()], 
        ['name'=>'company-bar','guard_name'=>'web','display_name'=>'company bar','slug'=>'','category'=>'sidebars','description'=>'company bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'dispatcher-request-bar','guard_name'=>'web','display_name'=>'dispatcher request','slug'=>'','category'=>'sidebars','description'=>'dispatcher request','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'request-list-bar','guard_name'=>'web','display_name'=>'','slug'=>'','category'=>'sidebars','description'=>'request list bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'cancelled-request-bar','guard_name'=>'web','display_name'=>'cancelled request bar','slug'=>'','category'=>'sidebars','description'=>'cancelled request bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'outstation-bar','guard_name'=>'web','display_name'=>'outstation bar','slug'=>'','category'=>'sidebars','description'=>'outstation bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'outstation-master-bar','guard_name'=>'web','display_name'=>'outstation master bar','slug'=>'','category'=>'sidebars','description'=>'outstation master bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'outstation-setprice-bar','guard_name'=>'web','display_name'=>'','slug'=>'','category'=>'sidebars','description'=>'outstation setprice bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'zone-management-bar','guard_name'=>'web','display_name'=>'zone management bar','slug'=>'','category'=>'sidebars','description'=>'zone management bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'zone-bar','guard_name'=>'web','display_name'=>'zone bar','slug'=>'','category'=>'sidebars','description'=>'zone bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'outofzone-bar','guard_name'=>'web','display_name'=>'outofzone bar','slug'=>'','category'=>'sidebars','description'=>'outofzone bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'rental-bar','guard_name'=>'web','display_name'=>'rental bar','slug'=>'','category'=>'sidebars','description'=>'rental bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'rental-list-bar','guard_name'=>'web','display_name'=>'rental list bar','slug'=>'','category'=>'sidebars','description'=>'rental list bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'masters-bar','guard_name'=>'web','display_name'=>'masters bar','slug'=>'','category'=>'sidebars','description'=>'masters bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'masters-vehicle-bar','guard_name'=>'web','display_name'=>'masters vehicle bar','slug'=>'','category'=>'sidebars','description'=>'masters vehicle bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'masters-vehiclemodel-bar','guard_name'=>'web','display_name'=>'masters vehiclemodel bar','slug'=>'','category'=>'sidebars','description'=>'masters vehiclemodel bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'masters-document-bar','guard_name'=>'web','display_name'=>'masters document bar','slug'=>'','category'=>'sidebars','description'=>'masters document bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'masters-category-bar','guard_name'=>'web','display_name'=>'masters category bar','slug'=>'','category'=>'sidebars','description'=>'masters category bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'support-sos-bar','guard_name'=>'web','display_name'=>'support sos bar','slug'=>'','category'=>'sidebars','description'=>'support sos bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'support-cancelreason-bar','guard_name'=>'web','display_name'=>'support cancelreason bar','slug'=>'','category'=>'sidebars','description'=>'support cancelreason bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'benefits-target','guard_name'=>'web','display_name'=>'benefits target','slug'=>'','category'=>'sidebars','description'=>'benefits target','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'benefits-promo','guard_name'=>'web','display_name'=>'benefits promo','slug'=>'','category'=>'sidebars','description'=>'benefits promo','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'promotion','guard_name'=>'web','display_name'=>'promotion','slug'=>'','category'=>'sidebars','description'=>'promotion','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'promotion-notification','guard_name'=>'web','display_name'=>'promotion notification','slug'=>'','category'=>'sidebars','description'=>'promotion-notification','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'others-pushtranslation','guard_name'=>'web','display_name'=>'others pushtranslation','slug'=>'','category'=>'sidebars','description'=>'others pushtranslation','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'others-reference','guard_name'=>'web','display_name'=>'others reference','slug'=>'','category'=>'sidebars','description'=>'others reference','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-role','guard_name'=>'web','display_name'=>'New Role','slug'=>'new-role','category'=>'roles','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'role-list','guard_name'=>'web','display_name'=>'Role list','slug'=>'role-list','category'=>'roles','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-role','guard_name'=>'web','display_name'=>'Edit Role','slug'=>'edit-role','category'=>'roles','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-role','guard_name'=>'web','display_name'=>'Delete Role','slug'=>'delete-role','category'=>'roles','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'assign-role-permission','guard_name'=>'web','display_name'=>'Assign Role to Permission','slug'=>'assign-role-permission','category'=>'roles','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'list-permission','guard_name'=>'web','display_name'=>'Permission List','slug'=>'list-permission','category'=>'permission','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'add-new-permission','guard_name'=>'web','display_name'=>'New Permssion','slug'=>'add-new-permission','category'=>'permission','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-permission','guard_name'=>'web','display_name'=>'Edit Permission','slug'=>'edit-permission','category'=>'permission','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-permission','guard_name'=>'web','display_name'=>'Delete the Permission','slug'=>'delete-permission','category'=>'permission','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'list-version','guard_name'=>'web','display_name'=>'Version List','slug'=>'list-version','category'=>'version','description'=>'Version List','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'add-new-version','guard_name'=>'web','display_name'=>'Add new Version','slug'=>'add-new-version','category'=>'version','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-version','guard_name'=>'web','display_name'=>'Edit Version','slug'=>'edit-version','category'=>'version','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-version','guard_name'=>'web','display_name'=>'Delete Version','slug'=>'delete-version','category'=>'version','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-complaints','guard_name'=>'web','display_name'=>'new complaints','slug'=>'new-complaint','category'=>'complaints','description'=>'adding new complaints','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-complaints','guard_name'=>'web','display_name'=>'edit complaints','slug'=>'edit-complaint','category'=>'complaints','description'=>'editing complaints','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-complaints','guard_name'=>'web','display_name'=>'delete complaints','slug'=>'delete-complaint','category'=>'complaints','description'=>'deleting complaints','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'status-change-complaints','guard_name'=>'web','display_name'=>'Status Change Complaint','slug'=>'status-change-complaint','category'=>'complaint','description'=>'Status Change Complaint','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-language','guard_name'=>'web','display_name'=>'New Language','slug'=>'new-language','category'=>'language','description'=>'New Language','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-language','guard_name'=>'web','display_name'=>'Edit Language','slug'=>'edit-language','category'=>'language','description'=>'Edit Language','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-language','guard_name'=>'web','display_name'=>'Delete Language','slug'=>'delete-language','category'=>'language','description'=>'Delete Language','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'status-change-language','guard_name'=>'web','display_name'=>'Status Change Language','slug'=>'status-change-language','category'=>'language','description'=>'Status Change Language','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-driver','guard_name'=>'web','display_name'=>'New Driver','slug'=>'new-driver','category'=>'driver','description'=>'New Driver','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-driver','guard_name'=>'web','display_name'=>'Edit Driver','slug'=>'edit-driver','category'=>'driver','description'=>'Edit Driver','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-driver','guard_name'=>'web','display_name'=>'Delete Driver','slug'=>'delete-driver','category'=>'driver','description'=>'Delete Driver','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'active-driver','guard_name'=>'web','display_name'=>'Active Driver','slug'=>'active-driver','category'=>'driver','description'=>'Active Driver','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-faq','guard_name'=>'web','display_name'=>'new faq','slug'=>'new-faq','category'=>'faq','description'=>'adding new faq','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-faq','guard_name'=>'web','display_name'=>'edit faq','slug'=>'edit-faq','category'=>'faq','description'=>'editing faq','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-faq','guard_name'=>'web','display_name'=>'delete faq','slug'=>'delete-faq','category'=>'faq','description'=>'deleting faq','created_at'=>NOW(),'updated_at'=>NOW()],
        // ['name'=>'view-faq','guard_name'=>'web','display_name'=>'View FAQ','slug'=>'view-faq','category'=>'faq','description'=>'View FAQ','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'status-change-faq','guard_name'=>'web','display_name'=>'status change faq','slug'=>'active-faq','category'=>'faq','description'=>'changing status for faq','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-sos','guard_name'=>'web','display_name'=>'new sos','slug'=>'new-sos','category'=>'sos','description'=>'add new sos','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-sos','guard_name'=>'web','display_name'=>'edit sos user','slug'=>'edit-sos','category'=>'sos','description'=>'editing the user of sos SOS','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-sos','guard_name'=>'web','display_name'=>'delete user','slug'=>'view-sos','category'=>'sos','description'=>'delete user of sos','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'status-change-sos','guard_name'=>'web','display_name'=>'status changer','slug'=>'active-sos','category'=>'sos','description'=>'changing the status','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-type','guard_name'=>'web','display_name'=>'add new vehicle','slug'=>'new-type','category'=>'vehicle','description'=>'adding new vehicle','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-type','guard_name'=>'web','display_name'=>'edit vehicle type','slug'=>'edit-type','category'=>'vehicle','description'=>'editing the type of vehicle','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-type','guard_name'=>'web','display_name'=>'delete vehicle type','slug'=>'delete-type','category'=>'vehicle','description'=>'deleting the type of vehicle','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'active-type','guard_name'=>'web','display_name'=>'active vehicle status','slug'=>'active-type','category'=>'vehicle','description'=>'changing vehicle status','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'add-zone','guard_name'=>'web','display_name'=>'Zone Mangement','slug'=>'','category'=>'zone','description'=>'adding new zone','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-zone','guard_name'=>'web','display_name'=>'Zone','slug'=>'','category'=>'zone','description'=>'zone editing','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'zone-surge-price','guard_name'=>'web','display_name'=>'surge price','slug'=>'','category'=>'zone','description'=>'surge price for zone','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'view-map-zone','guard_name'=>'web','display_name'=>'view zone map','slug'=>'','category'=>'zone','description'=>'viewing map','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'active-zone','guard_name'=>'web','display_name'=>'active zone','slug'=>'','category'=>'zone','description'=>'make active','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-zone','guard_name'=>'web','display_name'=>'delete zone','slug'=>'','category'=>'','description'=>'deleting zone','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-notification','guard_name'=>'web','display_name'=>'add new notify','slug'=>'','category'=>'notification','description'=>'sgd','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-notification','guard_name'=>'web','display_name'=>'delete notification','slug'=>'','category'=>'notification','description'=>'deleting notification','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-document','guard_name'=>'web','display_name'=>'new document','slug'=>'','category'=>'documents','description'=>'add new document','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-document','guard_name'=>'web','display_name'=>'edit document','slug'=>'','category'=>'documents','description'=>'document edit','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-document','guard_name'=>'web','display_name'=>'delete documents','slug'=>'','category'=>'documents','description'=>'deleting documents','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'active-document','guard_name'=>'web','display_name'=>'active document status','slug'=>'','category'=>'documents','description'=>'changing document status','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-cancelreason','guard_name'=>'web','display_name'=>'new reason category','slug'=>'','category'=>'cancellation_reasons','description'=>'adding new reason','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-cancelreason','guard_name'=>'web','display_name'=>'edit reason','slug'=>'','category'=>'cancellation_reasons','description'=>'editing reason','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-cancelreason','guard_name'=>'web','display_name'=>'delete reason','slug'=>'','category'=>'cancellation_reasons','description'=>'deleting reasons','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'active-cancelreason','guard_name'=>'web','display_name'=>'active reason status','slug'=>'','category'=>'cancellation_reasons','description'=>'changing status of reason','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-category','guard_name'=>'web','display_name'=>'new category','slug'=>'','category'=>'category','description'=>'adding new category','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-category','guard_name'=>'web','display_name'=>'edit category','slug'=>'','category'=>'category','description'=>'editing category','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-category','guard_name'=>'web','display_name'=>'delete category','slug'=>'','category'=>'category','description'=>'deleting category','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'active-category','guard_name'=>'web','display_name'=>'active category','slug'=>'','category'=>'category','description'=>'active category status','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-target','guard_name'=>'web','display_name'=>'new target','slug'=>'','category'=>'target_management','description'=>'adding new target','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-target','guard_name'=>'web','display_name'=>'delete target','slug'=>'','category'=>'target_management','description'=>'deleting target','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'status-change-target','guard_name'=>'web','display_name'=>'status for target','slug'=>'','category'=>'target_management','description'=>'changing status for target','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-promocode','guard_name'=>'web','display_name'=>'new promocode','slug'=>'','category'=>'promocode','description'=>'adding new promo code','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-promocode','guard_name'=>'web','display_name'=>'delete promocode','slug'=>'','category'=>'promocode','description'=>'deleting promo code','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'status-change-promocode','guard_name'=>'web','display_name'=>'status change promocode','slug'=>'','category'=>'promocode','description'=>'changing status for promocode','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'new-subscription','guard_name'=>'web','display_name'=>'new subscription','slug'=>'','category'=>'submaster','description'=>'adding new subscription','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'edit-subscription','guard_name'=>'web','display_name'=>'edit subscription','slug'=>'','category'=>'submaster','description'=>'editing subscription','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-subscription','guard_name'=>'web','display_name'=>'delete subscription','slug'=>'','category'=>'submaster','description'=>'deleting subscription','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'status-change-country','guard_name'=>'web','display_name'=>'status change country','slug'=>'','category'=>'country','description'=>'changing status for country','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'add-new-translation','guard_name'=>'web','display_name'=>'add new translation','slug'=>'','category'=>'languages','description'=>'new translation','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'translation-list','guard_name'=>'web','display_name'=>'translation list','slug'=>'','category'=>'languages','description'=>'list of translation','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'delete-translation','guard_name'=>'web','display_name'=>'delete translation','slug'=>'','category'=>'languages','description'=>'deleting translation','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'admin-bar','guard_name'=>'web','display_name'=>'Admin Bar','slug'=>'','category'=>'sidebars','description'=>'Admin bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'user-bar','guard_name'=>'web','display_name'=>'User Bar','slug'=>'','category'=>'sidebars','description'=>'user bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'driver-bar','guard_name'=>'web','display_name'=>'driver bar','slug'=>'','category'=>'sidebars','description'=>'driver management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'dispatcher-bar','guard_name'=>'web','display_name'=>'dispatcher bar','slug'=>'','category'=>'sidebars','description'=>'dispatcher management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'others-bar','guard_name'=>'web','display_name'=>'others bar','slug'=>'','category'=>'sidebars','description'=>'others','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'others-privilege','guard_name'=>'web','display_name'=>'others privilege','slug'=>'','category'=>'sidebars','description'=>'privilege management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'others-privilege-roles','guard_name'=>'web','display_name'=>'roles management','slug'=>'','category'=>'sidebars','description'=>'roles management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'others-privilege-permissions','guard_name'=>'web','display_name'=>'permissions management','slug'=>'','category'=>'sidebars','description'=>'permissions management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'others-language','guard_name'=>'web','display_name'=>'language management','slug'=>'','category'=>'sidebars','description'=>'language management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'others-country','guard_name'=>'web','display_name'=>'country management','slug'=>'','category'=>'sidebars','description'=>'country management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'others-translation','guard_name'=>'web','display_name'=>'translation management','slug'=>'','category'=>'sidebars','description'=>'translation management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'others-projectversion','guard_name'=>'web','display_name'=>'version management','slug'=>'','category'=>'sidebars','description'=>'version management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'request-bar','guard_name'=>'web','display_name'=>'request managemet','slug'=>'','category'=>'sidebars','description'=>'request managemet','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'support-bar','guard_name'=>'web','display_name'=>'support management','slug'=>'','category'=>'sidebars','description'=>'support management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'support-complaint-bar','guard_name'=>'web','display_name'=>'support complaint bar','slug'=>'','category'=>'sidebars','description'=>'support-complaint-bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'support-complaintlist-bar','guard_name'=>'web','display_name'=>'support complaintlist bar','slug'=>'','category'=>'sidebars','description'=>'support-complaintlist-bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'support-chat-bar','guard_name'=>'web','display_name'=>'support chat bar','slug'=>'','category'=>'sidebars','description'=>'support chat bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'support-faq-bar','guard_name'=>'web','display_name'=>'support faq bar','slug'=>'','category'=>'sidebars','description'=>'support faq bar','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'master-bar','guard_name'=>'web','display_name'=>'master management','slug'=>'','category'=>'sidebars','description'=>'master management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'master-zone','guard_name'=>'web','display_name'=>'zone management','slug'=>'','category'=>'sidebars','description'=>'zone management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'master-notification','guard_name'=>'web','display_name'=>'notification management','slug'=>'','category'=>'sidebars','description'=>'notification management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'master-sos','guard_name'=>'web','display_name'=>'sos management','slug'=>'','category'=>'sidebars','description'=>'sos management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'master-vehicle','guard_name'=>'web','display_name'=>'vehicle management','slug'=>'','category'=>'sidebars','description'=>'vehicle management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'master-document','guard_name'=>'web','display_name'=>'document management','slug'=>'','category'=>'sidebars','description'=>'document management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'master-cancelreason','guard_name'=>'web','display_name'=>'cancellation reason','slug'=>'','category'=>'sidebars','description'=>'cancellation reason','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'master-category','guard_name'=>'web','display_name'=>'category management','slug'=>'','category'=>'sidebars','description'=>'category management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'benefits-bar','guard_name'=>'web','display_name'=>'benefits management','slug'=>'','category'=>'sidebars','description'=>'benefits management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'subscription-bar','guard_name'=>'web','display_name'=>'subscription management','slug'=>'','category'=>'sidebars','description'=>'subscription management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'settings-bar','guard_name'=>'web','display_name'=>'settings management','slug'=>'','category'=>'sidebars','description'=>'settings management','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'dispatcher-history-bar','guard_name'=>'web','display_name'=>'dispatcher history bar','slug'=>'','category'=>'sidebars','description'=>'dispatcher history bar','created_at'=>NOW(),'updated_at'=>NOW()],   
        ['name'=>'new-push-notification','guard_name'=>'web','display_name'=>'add push notification','slug'=>'','category'=>'push','description'=>'add new push notification','created_at'=>NOW(),'updated_at'=>NOW()],         
        ['name'=>'edit-push','guard_name'=>'web','display_name'=>'Edit push notification','slug'=>'','category'=>'push','description'=>'edit push notification','created_at'=>NOW(),'updated_at'=>NOW()],           
        ['name'=>'delete-push','guard_name'=>'web','display_name'=>'Delete push notification','slug'=>'','category'=>'push','description'=>'delete push notification','created_at'=>NOW(),'updated_at'=>NOW()],           
        ['name'=>'status-change-push','guard_name'=>'web','display_name'=>'Status change push notification','slug'=>'','category'=>'push','description'=>'change status','created_at'=>NOW(),'updated_at'=>NOW()],           
        ['name'=>'master-push-notification','guard_name'=>'web','display_name'=>'master push notification','slug'=>'','category'=>'sidebars','description'=>'master push notification','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'create-dispatcher-bar','guard_name'=>'web','display_name'=>'create dispatcher bar','slug'=>'','category'=>'sidebars','description'=>'create dispatcher','created_at'=>NOW(),'updated_at'=>NOW()],
        ['name'=>'request-category-change','guard_name'=>'web','display_name'=>'request category change','slug'=>'','category'=>'request','description'=>'request category','created_at'=>NOW(),'updated_at'=>NOW()],   
        ['name'=>'fare-amount-details','guard_name'=>'web','display_name'=>'fare amount bar','slug'=>'','category'=>'sidebars','description'=>'fare amount details','created_at'=>NOW(),'updated_at'=>NOW()],    
        ['name'=>'block-drivers','guard_name'=>'web','display_name'=>'Block drivers','slug'=>'','category'=>'driver','description'=>'block drivers','created_at'=>NOW(),'updated_at'=>NOW()],
    );
    $slugs = new Permission();
    
    
    foreach($modules as $module){
        Permission::updateOrInsert([
            'name'=> $module['name'],
            'slug'=> Str::random(7)
        ],$module);
    }
    

        // DB::table('permissions')->truncate();
        // DB::table('permissions')->insert([
        //     ['name'=>'new-role','guard_name'=>'web','display_name'=>'New Role','slug'=>'new-role','category'=>'roles','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'role-list','guard_name'=>'web','display_name'=>'Role list','slug'=>'role-list','category'=>'roles','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-role','guard_name'=>'web','display_name'=>'Edit Role','slug'=>'edit-role','category'=>'roles','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-role','guard_name'=>'web','display_name'=>'Delete Role','slug'=>'delete-role','category'=>'roles','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'assign-role-permission','guard_name'=>'web','display_name'=>'Assign Role to Permission','slug'=>'assign-role-permission','category'=>'roles','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'list-permission','guard_name'=>'web','display_name'=>'Permission List','slug'=>'list-permission','category'=>'permission','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'add-new-permission','guard_name'=>'web','display_name'=>'New Permssion','slug'=>'add-new-permission','category'=>'permission','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-permission','guard_name'=>'web','display_name'=>'Edit Permission','slug'=>'edit-permission','category'=>'permission','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-permission','guard_name'=>'web','display_name'=>'Delete the Permission','slug'=>'delete-permission','category'=>'permission','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'list-version','guard_name'=>'web','display_name'=>'Version List','slug'=>'list-version','category'=>'version','description'=>'Version List','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'add-new-version','guard_name'=>'web','display_name'=>'Add new Version','slug'=>'add-new-version','category'=>'version','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-version','guard_name'=>'web','display_name'=>'Edit Version','slug'=>'edit-version','category'=>'version','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-version','guard_name'=>'web','display_name'=>'Delete Version','slug'=>'delete-version','category'=>'version','description'=>'','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-complaints','guard_name'=>'web','display_name'=>'new complaints','slug'=>'new-complaint','category'=>'complaints','description'=>'adding new complaints','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-complaints','guard_name'=>'web','display_name'=>'edit complaints','slug'=>'edit-complaint','category'=>'complaints','description'=>'editing complaints','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-complaints','guard_name'=>'web','display_name'=>'delete complaints','slug'=>'delete-complaint','category'=>'complaints','description'=>'deleting complaints','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'status-change-complaints','guard_name'=>'web','display_name'=>'Status Change Complaint','slug'=>'status-change-complaint','category'=>'complaint','description'=>'Status Change Complaint','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-language','guard_name'=>'web','display_name'=>'New Language','slug'=>'new-language','category'=>'language','description'=>'New Language','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-language','guard_name'=>'web','display_name'=>'Edit Language','slug'=>'edit-language','category'=>'language','description'=>'Edit Language','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-language','guard_name'=>'web','display_name'=>'Delete Language','slug'=>'delete-language','category'=>'language','description'=>'Delete Language','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'status-change-language','guard_name'=>'web','display_name'=>'Status Change Language','slug'=>'status-change-language','category'=>'language','description'=>'Status Change Language','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-driver','guard_name'=>'web','display_name'=>'New Driver','slug'=>'new-driver','category'=>'driver','description'=>'New Driver','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-driver','guard_name'=>'web','display_name'=>'Edit Driver','slug'=>'edit-driver','category'=>'driver','description'=>'Edit Driver','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-driver','guard_name'=>'web','display_name'=>'Delete Driver','slug'=>'delete-driver','category'=>'driver','description'=>'Delete Driver','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'active-driver','guard_name'=>'web','display_name'=>'Active Driver','slug'=>'active-driver','category'=>'driver','description'=>'Active Driver','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-faq','guard_name'=>'web','display_name'=>'new faq','slug'=>'new-faq','category'=>'faq','description'=>'adding new faq','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-faq','guard_name'=>'web','display_name'=>'edit faq','slug'=>'edit-faq','category'=>'faq','description'=>'editing faq','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-faq','guard_name'=>'web','display_name'=>'delete faq','slug'=>'delete-faq','category'=>'faq','description'=>'deleting faq','created_at'=>NOW(),'updated_at'=>NOW()],
        //     // ['name'=>'view-faq','guard_name'=>'web','display_name'=>'View FAQ','slug'=>'view-faq','category'=>'faq','description'=>'View FAQ','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'status-change-faq','guard_name'=>'web','display_name'=>'status change faq','slug'=>'active-faq','category'=>'faq','description'=>'changing status for faq','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-sos','guard_name'=>'web','display_name'=>'new sos','slug'=>'new-sos','category'=>'sos','description'=>'add new sos','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-sos','guard_name'=>'web','display_name'=>'edit sos user','slug'=>'edit-sos','category'=>'sos','description'=>'editing the user of sos SOS','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-sos','guard_name'=>'web','display_name'=>'delete user','slug'=>'view-sos','category'=>'sos','description'=>'delete user of sos','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'status-change-sos','guard_name'=>'web','display_name'=>'status changer','slug'=>'active-sos','category'=>'sos','description'=>'changing the status','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-type','guard_name'=>'web','display_name'=>'add new vehicle','slug'=>'new-type','category'=>'vehicle','description'=>'adding new vehicle','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-type','guard_name'=>'web','display_name'=>'edit vehicle type','slug'=>'edit-type','category'=>'vehicle','description'=>'editing the type of vehicle','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-type','guard_name'=>'web','display_name'=>'delete vehicle type','slug'=>'delete-type','category'=>'vehicle','description'=>'deleting the type of vehicle','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'active-type','guard_name'=>'web','display_name'=>'active vehicle status','slug'=>'active-type','category'=>'vehicle','description'=>'changing vehicle status','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'add-zone','guard_name'=>'web','display_name'=>'Zone Mangement','slug'=>'','category'=>'zone','description'=>'adding new zone','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-zone','guard_name'=>'web','display_name'=>'Zone','slug'=>'','category'=>'zone','description'=>'zone editing','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'zone-surge-price','guard_name'=>'web','display_name'=>'surge price','slug'=>'','category'=>'zone','description'=>'surge price for zone','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'view-map-zone','guard_name'=>'web','display_name'=>'view zone map','slug'=>'','category'=>'zone','description'=>'viewing map','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'active-zone','guard_name'=>'web','display_name'=>'active zone','slug'=>'','category'=>'zone','description'=>'make active','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-zone','guard_name'=>'web','display_name'=>'delete zone','slug'=>'','category'=>'','description'=>'deleting zone','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-notification','guard_name'=>'web','display_name'=>'add new notify','slug'=>'','category'=>'notification','description'=>'sgd','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-notification','guard_name'=>'web','display_name'=>'delete notification','slug'=>'','category'=>'notification','description'=>'deleting notification','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-document','guard_name'=>'web','display_name'=>'new document','slug'=>'','category'=>'documents','description'=>'add new document','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-document','guard_name'=>'web','display_name'=>'edit document','slug'=>'','category'=>'documents','description'=>'document edit','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-document','guard_name'=>'web','display_name'=>'delete documents','slug'=>'','category'=>'documents','description'=>'deleting documents','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'active-document','guard_name'=>'web','display_name'=>'active document status','slug'=>'','category'=>'documents','description'=>'changing document status','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-cancelreason','guard_name'=>'web','display_name'=>'new reason category','slug'=>'','category'=>'cancellation_reasons','description'=>'adding new reason','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-cancelreason','guard_name'=>'web','display_name'=>'edit reason','slug'=>'','category'=>'cancellation_reasons','description'=>'editing reason','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-cancelreason','guard_name'=>'web','display_name'=>'delete reason','slug'=>'','category'=>'cancellation_reasons','description'=>'deleting reasons','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'active-cancelreason','guard_name'=>'web','display_name'=>'active reason status','slug'=>'','category'=>'cancellation_reasons','description'=>'changing status of reason','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-category','guard_name'=>'web','display_name'=>'new category','slug'=>'','category'=>'category','description'=>'adding new category','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-category','guard_name'=>'web','display_name'=>'edit category','slug'=>'','category'=>'category','description'=>'editing category','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-category','guard_name'=>'web','display_name'=>'delete category','slug'=>'','category'=>'category','description'=>'deleting category','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'active-category','guard_name'=>'web','display_name'=>'active category','slug'=>'','category'=>'category','description'=>'active category status','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-target','guard_name'=>'web','display_name'=>'new target','slug'=>'','category'=>'target_management','description'=>'adding new target','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-target','guard_name'=>'web','display_name'=>'delete target','slug'=>'','category'=>'target_management','description'=>'deleting target','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'status-change-target','guard_name'=>'web','display_name'=>'status for target','slug'=>'','category'=>'target_management','description'=>'changing status for target','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-promocode','guard_name'=>'web','display_name'=>'new promocode','slug'=>'','category'=>'promocode','description'=>'adding new promo code','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-promocode','guard_name'=>'web','display_name'=>'delete promocode','slug'=>'','category'=>'promocode','description'=>'deleting promo code','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'status-change-promocode','guard_name'=>'web','display_name'=>'status change promocode','slug'=>'','category'=>'promocode','description'=>'changing status for promocode','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'new-subscription','guard_name'=>'web','display_name'=>'new subscription','slug'=>'','category'=>'submaster','description'=>'adding new subscription','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'edit-subscription','guard_name'=>'web','display_name'=>'edit subscription','slug'=>'','category'=>'submaster','description'=>'editing subscription','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-subscription','guard_name'=>'web','display_name'=>'delete subscription','slug'=>'','category'=>'submaster','description'=>'deleting subscription','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'status-change-country','guard_name'=>'web','display_name'=>'status change country','slug'=>'','category'=>'country','description'=>'changing status for country','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'add-new-translation','guard_name'=>'web','display_name'=>'add new translation','slug'=>'','category'=>'languages','description'=>'new translation','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'translation-list','guard_name'=>'web','display_name'=>'translation list','slug'=>'','category'=>'languages','description'=>'list of translation','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'delete-translation','guard_name'=>'web','display_name'=>'delete translation','slug'=>'','category'=>'languages','description'=>'deleting translation','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'admin-bar','guard_name'=>'web','display_name'=>'Admin Bar','slug'=>'','category'=>'sidebars','description'=>'Admin bar','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'user-bar','guard_name'=>'web','display_name'=>'User Bar','slug'=>'','category'=>'sidebars','description'=>'user bar','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'driver-bar','guard_name'=>'web','display_name'=>'driver bar','slug'=>'','category'=>'sidebars','description'=>'driver management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'dispatcher-bar','guard_name'=>'web','display_name'=>'dispatcher bar','slug'=>'','category'=>'sidebars','description'=>'dispatcher management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'others-bar','guard_name'=>'web','display_name'=>'others bar','slug'=>'','category'=>'sidebars','description'=>'others','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'others-privilege','guard_name'=>'web','display_name'=>'others privilege','slug'=>'','category'=>'sidebars','description'=>'privilege management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'others-privilege-roles','guard_name'=>'web','display_name'=>'roles management','slug'=>'','category'=>'sidebars','description'=>'roles management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'others-privilege-permissions','guard_name'=>'web','display_name'=>'permissions management','slug'=>'','category'=>'sidebars','description'=>'permissions management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'others-language','guard_name'=>'web','display_name'=>'language management','slug'=>'','category'=>'sidebars','description'=>'language management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'others-country','guard_name'=>'web','display_name'=>'country management','slug'=>'','category'=>'sidebars','description'=>'country management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'others-translation','guard_name'=>'web','display_name'=>'translation management','slug'=>'','category'=>'sidebars','description'=>'translation management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'others-projectversion','guard_name'=>'web','display_name'=>'version management','slug'=>'','category'=>'sidebars','description'=>'version management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'request-bar','guard_name'=>'web','display_name'=>'request managemet','slug'=>'','category'=>'sidebars','description'=>'request managemet','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'support-bar','guard_name'=>'web','display_name'=>'support management','slug'=>'','category'=>'sidebars','description'=>'support management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'support-complaint','guard_name'=>'web','display_name'=>'complaint management','slug'=>'','category'=>'sidebars','description'=>'complaint management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'support-user-complaint','guard_name'=>'web','display_name'=>'user complaint management','slug'=>'','category'=>'sidebars','description'=>'user complaint management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'support-chat','guard_name'=>'web','display_name'=>'chat management','slug'=>'','category'=>'sidebars','description'=>'chat management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'support-faq','guard_name'=>'web','display_name'=>'faq management','slug'=>'','category'=>'sidebars','description'=>'faq management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'master-bar','guard_name'=>'web','display_name'=>'master management','slug'=>'','category'=>'sidebars','description'=>'master management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'master-zone','guard_name'=>'web','display_name'=>'zone management','slug'=>'','category'=>'sidebars','description'=>'zone management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'master-notification','guard_name'=>'web','display_name'=>'notification management','slug'=>'','category'=>'sidebars','description'=>'notification management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'master-sos','guard_name'=>'web','display_name'=>'sos management','slug'=>'','category'=>'sidebars','description'=>'sos management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'master-vehicle','guard_name'=>'web','display_name'=>'vehicle management','slug'=>'','category'=>'sidebars','description'=>'vehicle management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'master-document','guard_name'=>'web','display_name'=>'document management','slug'=>'','category'=>'sidebars','description'=>'document management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'master-cancelreason','guard_name'=>'web','display_name'=>'cancellation reason','slug'=>'','category'=>'sidebars','description'=>'cancellation reason','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'master-category','guard_name'=>'web','display_name'=>'category management','slug'=>'','category'=>'sidebars','description'=>'category management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'benefits-bar','guard_name'=>'web','display_name'=>'benefits management','slug'=>'','category'=>'sidebars','description'=>'benefits management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'subscription-bar','guard_name'=>'web','display_name'=>'subscription management','slug'=>'','category'=>'sidebars','description'=>'subscription management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'settings-bar','guard_name'=>'web','display_name'=>'settings management','slug'=>'','category'=>'sidebars','description'=>'settings management','created_at'=>NOW(),'updated_at'=>NOW()],
        //     ['name'=>'dispatcher-history-bar','guard_name'=>'web','display_name'=>'dispatcher history bar','slug'=>'','category'=>'sidebars','description'=>'dispatcher history bar','created_at'=>NOW(),'updated_at'=>NOW()],   
        //     ['name'=>'new-push-notification','guard_name'=>'web','display_name'=>'add push notification','slug'=>'','category'=>'push','description'=>'add new push notification','created_at'=>NOW(),'updated_at'=>NOW()],         
        //     ['name'=>'edit-push','guard_name'=>'web','display_name'=>'Edit push notification','slug'=>'','category'=>'push','description'=>'edit push notification','created_at'=>NOW(),'updated_at'=>NOW()],           
        //     ['name'=>'delete-push','guard_name'=>'web','display_name'=>'Delete push notification','slug'=>'','category'=>'push','description'=>'delete push notification','created_at'=>NOW(),'updated_at'=>NOW()],           
        //     ['name'=>'status-change-push','guard_name'=>'web','display_name'=>'Status change push notification','slug'=>'','category'=>'push','description'=>'change status','created_at'=>NOW(),'updated_at'=>NOW()],           
        //     ['name'=>'master-push-notification','guard_name'=>'web','display_name'=>'master push notification','slug'=>'','category'=>'sidebars','description'=>'master push notification','created_at'=>NOW(),'updated_at'=>NOW()],           

        // ]);

    }
}